### ISSUE TITLE
Missing `import_map.generated.js` on `deno.land/x`

### ISSUE THREAD

**Issue by hasundue** [denoland/import_map#60]
Apparently deployment of the latest version to `deno.land/x` had a problem and you cannot find a default module or documentation on the page: https://deno.land/x/import_map@v0.17.0?doc

You can still import the module from https://deno.land/x/import_map@v0.17.0/js/mod.ts but `import_map.generated.js` is missing, resulting in a runtime error on import.

I'm issuing this in case the team is not aware of it.

**Comment by deer** [comment]
@dsherret @yacinehmito, can you please take a look at this? I suspect something went wrong with #59.

For comparison:
* https://deno.land/x/emit@0.34.0?source
* https://deno.land/x/deno_graph@0.63.6?source
* https://deno.land/x/import_map@v0.18.2?source

import_map is missing the `.wasm` and `.generated.js` files.

Instead they've snuck into a mysterious https://deno.land/x/import_map@deno%2Fv0.18.2?source, with the strange version of `deno/v0.18.2`, which doesn't seem right. A closer look at `git tag` in the three repositories hints at a problem:

deno_emit:
```
...
0.33.0
0.34.0
...
0.9.0
...
deno/0.33.0
deno/0.34.0
```

deno_graph
```
...
0.63.5
0.63.6
...
0.9.1
...
deno/0.63.5
deno/0.63.6
```

import_map
```
deno/v0.18.0
deno/v0.18.1
deno/v0.18.2
...
v0.18.1
v0.18.2
...
v0.9.0
```

The projects without `v` in their tags and versions get published correctly, but `import_map` isn't. I almost stopped here, but then decided to challenge myself. On to https://github.com/denoland/automation.

I'm not sure where these `deno/` versions came from, but they're causing a problem here: https://github.com/denoland/automation/blob/c427dafbb747ca4e27149306376aa0d1b71bda78/helpers.ts#L56
Then it's not able to parse the version, and I guess the combination of dax / github actions / whatever is leading to the error getting swallowed.

When I modify this locally to instead be
```ts
const version = semver.parse(name.replace(/^v/, "").replace(/^deno\//, ""));
```
then I'm able to run `publish_release.ts` successfully. I get the following (some stuff cut out for brevity):
```
deno run -A ../automation/tasks/publish_release.ts --patch import_map
Committing...
Pushing to main...
Tagging v0.18.3...

deno run -A ../automation/tasks/publish_release.ts --patch deno_graph
Committing...
Pushing to main...
Tagging 0.63.7...

deno run -A ../automation/tasks/publish_release.ts --patch deno_emit
Committing...
Pushing to main...
Tagging 0.34.1...
```

I'll open a PR in `automation` to amend the script accordingly, although it would be good to know where these problematic `deno/` versions are coming from. Additionally, I'll open PRs to update these projects. All three are using massively outdated versions of the `publish_release` script in their CI.

**Comment by dsherret** [comment]
The fix here was to update the import_map webhook to specify a version_prefix of `deno/`:

https://api.deno.land/webhook/gh/import_map?version_prefix=deno/

I've gone ahead and done that and published a new release: https://deno.land/x/import_map@v0.18.3/mod.ts

The current setup for doing these publishes is very bad. It will be better with in the upcoming Deno registry where we can actually publish folders that are built rather than relying on building to branches and doing these hacky tag stuff, which is a lot of complexity.
